### ISSUE TITLE
Component: Photo Caption

### ISSUE THREAD

**Issue by aleesteele** [CSIS-iLab/on-the-radar#103]
- [x] Photo caption with icon. Should account for links.

**Comment by leezaweb** [comment]
@aleesteele I committed a fix for this to the feature/photo-caption branch in December. I don't know where that went, but since I had it on my local I just stashed the changes, deleted the branch, re-retrieved it and added the commits: https://github.com/CSIS-iLab/on-the-radar/pull/104

For the record, @jnschrag Tucker said that this should be a wysiwyg field.

**Comment by jnschrag** [comment]
@leezaweb Sounds good, thank you. Left a review on #104
