### ISSUE TITLE
Design Tweaks

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#125]
*Note that Tucker will add on to this issue as she reviews the site. Jacque will assign items once all have been added to the checklist.*

## Post Content
- [x] Check margins on headings (bottom margin should be 1rem) **Jacque**
- [x] Remove bottom margin from last child **Jacque**

----
_*Tucker's additions_
📱 = mobile (or when mobile functionalities kick in)
🖥 = desktop (large)

## Header
- [x] on scroll up header: the search icon and the nav items should be vertically aligned center  **Leeza**
- [x] on scroll up header: the header does a weird jumpy thing when appearing after the first time you scroll up from leaving the top...it looks like it's shrinking for a second
  - **Note:** The `site-header--minimal` class needs to be added any time the header isn't at the top of the page. That's what shrinks it down & is causing the jump when it switches from hidden to visible for the first time.
- [x] make color of active search text (not the placeholder text) `#fff`  **Leeza**
- [x] in search: vertically center the "X" in the container  **Leeza**

## Post
- [x] 🖥 max-width for the post meta at the top (date, authors, last updated, photo caption): 3/4 of content  **Leeza**
- [x] 📱 Related Reading boxes should be full width on content : on small screens remove the max-width  **Leeza**
- [x] Related Reading @ bottom: some boxes get bigger an others 
- [x] remove the orangle triangle before the photo caption is there isn't a caption  **Leeza**
- [x] Author names are not appearing at the top of the post  **Leeza**
- [x] Remove "about the authors" at the bottom if no bios are set  **Leeza**
- [x] why do some posts have a divider between the content and footnotes?  **Leeza**

  ##### ANALYSIS:
- [x] The second item under "Related Briefs" isn't appearing, and the link for the triangle icon isn't set  **Leeza**

## Resources
- [x] when hovering over the title of an external link, the small icon should also turn orange  **Leeza**

## About
- [x] 🖥 Increase the padding at the top of the page (refer to mockups)  **Leeza**
- [x] remove the social icons under the page title  **Leeza**

## Archives
- [x] On pages with pagination, `page__footer.pagination:after` extends and increases the width of the pages (there is a horizontal scroll). I think it's affecting the other side, too, because there's a chunk of blue missing on the left.
- [x] What's up with the author archives? I realize i didn't have a mockup for them... Here's the idea:  **Leeza**
![Screen Shot 2019-07-18 at 2 43 39 PM](https://user-images.githubusercontent.com/13002217/61483360-a4eaf580-a96a-11e9-91ef-655ff6d409cd.png)
- [x] 🖥 add 3.5rem padding to bottom on archive__sidebar` (just in case the articles don't go past the list)  **Leeza**
- [x] Ellipses should be applied to excerpts after 48 words (or 340 characters... whichever is easiest)  **Leeza**

  ##### REFINE RESULTS:
    - [x] 🖥 can we start the page loaded with the first refinement block open?  **Leeza**
    - [x] when sidebar refinement block is extended: add  1.25rem margin to the last child in the list  **Leeza**
    - [x] 📱 When something is applied to the REFINE RESULTS, make that text look the same as the FILTER BY TYPE text (so...smaller)  **Leeza**
    - [x] 📱 Center the REFINE RESULTS text and arrow vertically in its box  **Leeza**
    - [x] 📱 increase the size of the font for the options to match the FILTER BY TYPE font size (15px)  **Leeza**

  ##### FILTER BY TYPE:
    - [x] 📱 Make the FILTER BY TYPE options Capitalized (not all-caps)  **Leeza**

  ##### Both FILTER BY TYPE and REFINE RESULTS:
    - [x] 📱 the whole block should be clickable
    - [x] 📱 increase top/bottom padding of list items to .25rem  **Leeza**

**Comment by tuckabelle** [comment]
⭐️= Tucker will do

## Issue Briefs
- [ ] 📱⭐️ filtering style 
- [ ]  filtering style 

## header
- [ ] give a little wiggle room for accidentally scrolling up and making the nav disappear 

## search
- [ ] ⭐️ faster animation 

## archive
- [ ] horizontal scroll/overflow  at about 600px
- [ ] clear all button not here if nothing to clear
- [ ]  For Country Profiles that have no refinements: put words (Further refinements unavailable)
- [ ] country profiles: the "clear all" button should only affect the refinements in the sidebar
- [ ] weird thing happens when on tech primers and you push "Clear All" button
- [ ] ⭐️ font size of refinement filter


## posts
- [ ] ⭐️ they are putting in horizontal lines in posts...let's set it so it looks better...
- [ ] ⭐️ remove letter-spacing in download brief button at bottom
- [ ] ⭐️ fix glossary styles
- [ ] ⭐️ no letter spacing in list items on sidebar
- [ ] 📱 ⭐️ min-height on featured images
- [ ] 💻 ⭐️ Downloads list in sidebar can be full-width
- [ ] 📱 make sure post meta font size doesn't go below 14px
- [ ] ⭐️ center up results text in orange: 
```
.archive__results, .post__header .post__content-type {
    position: relative;
    padding-top: 0.5rem;
    padding-bottom: 0.6rem;
```

## resources
- [ ] ⭐️ don't line break with external icon 
- [ ] ⭐️ less space b/t meta and description

## glossary
- [ ] still a weird chunk of the orange headings not reaching full height


## for the program
- hEaDIngS!
- don't need to have the heading "introduction" at the top of a post
- be consistent about when you put that horizontal line in before the footnotes. Either do it or don't.
- use bullet lists when necessary. Don't list in a paragraph (i.e. Resilient Communications for Command and Control of Nuclear Forces)
