### ISSUE TITLE
Component: Social Share

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#25]
Display the social media share icons for a post

- [x] Facebook
- [x] Twitter
- [x] LinkedIn
- [x] Email
- [x] Copy Link

**Comment by aleesteele** [comment]
Initial code base pushed, will edit when there is content.

**Comment by jnschrag** [comment]
@aleesteele Could you revisit this component some time this week or next?

**Comment by aleesteele** [comment]
@jnschrag Yep, absolutely!

**Comment by aleesteele** [comment]
@jnschrag Yep, absolutely!
A few questions:
1. Should I write a new mixin for the padding, so that the social share icons stick to the right side of the content, instead of adjusting dynamically w/ the pre-existing content?
2. With the 'share-link' icon, is there supposed to be any pre-defined behavior when someone clicks on it? Like a pop up that says 'copied', a modal with the link, etc.?

**Comment by jnschrag** [comment]
1. I would use absolute positioning for the icons in this case. They overlap multiple containers & grid items, so taking them out of the document flow is probably the better approach here.
2. Let's go with a "Copied" tooltip. If you look at the Health Commission website and look at the cite component that Leeza created, you'll see an example of the "copied" popup that we're going for. And I would recommend using that clipboard.js library to do this.
